lang_code={
    "English (Latin)": "eng_Latn",
    "Hindi (Devanagari)": "hin_Deva",
    "Bengali (Bengali)": "ben_Beng",
    "Arbëreshë Albanian (Latin)": "aae_Latn",
    "Afade (Latin)": "aal_Latn",
    "Abung (Latin)": "abb_Latn",
    "Abidji (Latin)": "abi_Latn",
    "Abkhazian (Cyrillic)": "abk_Cyrl",
    "Abua (Latin)": "abn_Latn",
    "Abellen Ayta (Latin)": "abp_Latn",
    "Abron (Latin)": "abr_Latn",
    "Ambulas (Latin)": "abs_Latn",
    "Achagua (Latin)": "aca_Latn",
    "Gikyode (Latin)": "acd_Latn",
    "Achinese (Latin)": "ace_Latn",
    "Saint Lucian Creole French (Latin)": "acf_Latn",
    "Acholi (Latin)": "ach_Latn",
    "Iraqi Arabic (Arabic)": "acm_Arab",
    "Achang (Latin)": "acn_Latn",
    "Achi (Latin)": "acr_Latn",
    "Achuar-Shiwiar (Latin)": "acu_Latn",
    "Hijazi Arabic (Arabic)": "acw_Arab",
    "Adele (Latin)": "ade_Latn",
    "Adhola (Latin)": "adh_Latn",
    "Adioukrou (Latin)": "adj_Latn",
    "Amdo Tibetan (Tibetan)": "adx_Tibt",
    "Adyghe (Cyrillic)": "ady_Cyrl",
    "Tunisian Arabic (Arabic)": "aeb_Arab",
    "Saidi Arabic (Arabic)": "aec_Arab",
    "Arem (Latin)": "aeu_Latn",
    "Gulf Arabic (Arabic)": "afb_Arab",
    "Eloyi (Latin)": "afo_Latn",
    "Afrikaans (Latin)": "afr_Latn",
    "Agarabi (Latin)": "agd_Latn",
    "Angor (Latin)": "agg_Latn",
    "Agariya (Latin)": "agn_Latn",
    "Aguaruna (Latin)": "agr_Latn",
    "Aguacateco (Latin)": "agu_Latn",
    "Agul (Cyrillic)": "agx_Cyrl",
    "Ahanta (Latin)": "aha_Latn",
    "Akha (Latin)": "ahk_Latn",
    "Igo (Latin)": "ahl_Latn",
    "Arosi (Latin)": "ahs_Latn",
    "Arosi (Latin)": "aia_Latn",
    "Aja (Benin) (Latin)": "ajg_Latn",
    "Akan (Latin)": "aka_Latn",
    "Batak Angkola (Latin)": "akb_Latn",
    "Akawaio (Latin)": "ake_Latn",
    "Akpes (Latin)": "akp_Latn",
    "Alago (Latin)": "ala_Latn",
    "Alangan (Latin)": "alj_Latn",
    "Gheg Albanian (Latin)": "aln_Latn",
    "Larike-Wakasihu (Latin)": "alo_Latn",
    "Alune (Latin)": "alp_Latn",
    "Tosk Albanian (Latin)": "als_Latn",
    "Southern Altai (Cyrillic)": "alt_Cyrl",
    "Alur (Latin)": "alz_Latn",
    "Amarasi (Latin)": "ame_Latn",
    "Hamer-Banna (Latin)": "amf_Latn",
    "Amharic (Ethiopic)": "amh_Ethi",
    "Amis (Latin)": "ami_Latn",
    "Amo (Latin)": "amk_Latn",
    "Amanab (Latin)": "amu_Latn",
    "Ngas (Latin)": "anc_Latn",
    "Goemai (Latin)": "ank_Latn",
    "Obolo (Latin)": "ann_Latn",
    "Angika (Devanagari)": "anp_Deva",
    "Anaang (Latin)": "anw_Latn",
    "Anyin (Latin)": "any_Latn",
    "A'ou (Latin)": "aom_Latn",
    "Uab Meto (Latin)": "aoz_Latn",
    "Sa'a (Latin)": "apb_Latn",
    "North Levantine Arabic (Arabic)": "apc_Arab",
    "Sudanese Arabic (Arabic)": "apd_Arab",
    "A-Pucikwar (Latin)": "apr_Latn",
    "Standard Arabic (Arabic)": "arb_Arab",
    "Aragonese (Latin)": "arg_Latn",
    "Arhâ (Latin)": "arl_Latn",
    "Algerian Arabic (Arabic)": "arq_Arab",
    "Najdi Arabic (Arabic)": "ars_Arab",
    "Moroccan Arabic (Arabic)": "ary_Arab",
    "Egyptian Arabic (Arabic)": "arz_Arab",
    "Asu (Tanzania) (Latin)": "asa_Latn",
    "Cishingini (Latin)": "asg_Latn",
    "Assamese (Bengali)": "asm_Beng",
    "Asturian (Latin)": "ast_Latn",
    "Ata (Latin)": "ata_Latn",
    "Atsi (Latin)": "atb_Latn",
    "Atong (India) (Latin)": "atg_Latn",
    "Ivbie North-Okpela-Arhe (Latin)": "ati_Latn",
    "Atikamekw (Latin)": "atq_Latn",
    "Avaric (Cyrillic)": "ava_Cyrl",
    "Avikam (Latin)": "avn_Latn",
    "Avokaya (Latin)": "avu_Latn",
    "Awadhi (Devanagari)": "awa_Deva",
    "Awa-Cuaiquer (Latin)": "awb_Latn",
    "Arawum (Latin)": "awo_Latn",
    "South Levantine Arabic (Arabic)": "ayl_Arab",
    "Ayizo Gbe (Latin)": "ayo_Latn",
    "North Mesopotamian Arabic (Arabic)": "ayp_Arab",
    "Aymara (Latin)": "ayr_Latn",
    "Mai Brat (Latin)": "ayz_Latn",
    "Azerbaijani (Arabic)": "aze_Arab",
    "Azerbaijani (Cyrillic)": "aze_Cyrl",
    "Azerbaijani (Latin)": "aze_Latn",
    "Ambele (Latin)": "azg_Latn",
    "Highland Oaxaca Chontal (Latin)": "azz_Latn",
    "Bagheli (Latin)": "bag_Latn",
    "Bashkir (Cyrillic)": "bak_Cyrl",
    "Bambara (Latin)": "bam_Latn",
    "Balinese (Latin)": "ban_Latn",
    "Waimaha (Latin)": "bao_Latn",
    "Basa (Cameroon) (Latin)": "bas_Latn",
    "Vengo (Latin)": "bav_Latn",
    "Bambili-Bambui (Latin)": "bax_Latn",
    "Barai (Latin)": "bba_Latn",
    "Baeggu (Latin)": "bbb_Latn",
    "Batak Toba (Latin)": "bbc_Latn",
    "Ghomálá' (Latin)": "bbj_Latn",
    "Babanki (Georgian)": "bbl_Geor",
    "Northern Bobo Madaré (Latin)": "bbo_Latn",
    "Kulung (Nigeria) (Latin)": "bbu_Latn",
    "Southern Balochi (Arabic)": "bcc_Arab",
    "Southern Balochi (Latin)": "bcc_Latn",
    "Bainouk-Samik (Latin)": "bce_Latn",
    "Baoulé (Latin)": "bci_Latn",
    "Central Bikol (Latin)": "bcl_Latn",
    "Bainouk-Gunyaamolo (Latin)": "bcs_Latn",
    "Bana (Latin)": "bcw_Latn",
    "Bannoni (Latin)": "bcy_Latn",
    "Bainouk-Gunyaamolo (Latin)": "bcz_Latn",
    "Bai (Latin)": "bda_Latn",
    "Bade (Latin)": "bde_Latn",
    "Balesin-Bisaya (Latin)": "bdg_Latn",
    "Baka (South Sudan) (Latin)": "bdh_Latn",
    "Burun (Latin)": "bdm_Latn",
    "Bau (Latin)": "bdq_Latn",
    "Oroko (Latin)": "bdu_Latn",
    "Bebele (Latin)": "beb_Latn",
    "Biali (Latin)": "beh_Latn",
    "Belarusian (Cyrillic)": "bel_Cyrl",
    "Bemba (Zambia) (Latin)": "bem_Latn",
    "Bengali (Bengali)": "ben_Beng",
    "Bila (Latin)": "bep_Latn",
    "Betawi (Latin)": "bew_Latn",
    "Yarawa (Latin)": "bex_Latn",
    "Beba (Latin)": "bfa_Latn",
    "Bafut (Latin)": "bfd_Latn",
    "Beba (Latin)": "bfo_Latn",
    "Balti (Arabic)": "bft_Arab",
    "Bagheli (Devanagari)": "bfy_Deva",
    "Pahari-Potwari (Devanagari)": "bfz_Deva",
    "Haryanvi (Devanagari)": "bgc_Deva",
    "Gwamhi-Wuri (Arabic)": "bgp_Arab",
    "Bagri (Devanagari)": "bgq_Deva",
    "Bauria (Latin)": "bgr_Latn",
    "Gamo-Gofa-Dawro (Latin)": "bgt_Latn",
    "Bhatri (Devanagari)": "bgw_Deva",
    "Bharia (Devanagari)": "bha_Deva",
    "Bhili (Devanagari)": "bhb_Deva",
    "Bukhari (Cyrillic)": "bhh_Cyrl",
    "Bhojpuri (Devanagari)": "bho_Deva",
    "Bima (Latin)": "bhp_Latn",
    "Bhattiyali (Devanagari)": "bht_Deva",
    "Biangai (Latin)": "bhz_Latn",
    "Bissa (Latin)": "bib_Latn",
    "Bimoba (Latin)": "bim_Latn",
    "Bislama (Latin)": "bis_Latn",
    "B Eliot (Latin)": "biv_Latn",
    "Badyara (Devanagari)": "bjj_Deva",
    "Barok (Latin)": "bjk_Latn",
    "Banjar (Latin)": "bjn_Latn",
    "Binumarien (Latin)": "bjr_Latn",
    "Bulu (Papua New Guinea) (Latin)": "bjt_Latn",
    "Bedjond (Latin)": "bjv_Latn",
    "Bakwé (Latin)": "bjw_Latn",
    "Bariji (Latin)": "bjz_Latn",
    "Binukid (Latin)": "bkd_Latn",
    "Bakoko (Latin)": "bkh_Latn",
    "Boki (Latin)": "bkm_Latn",
    "Bekwarra (Latin)": "bkv_Latn",
    "Bungku (Latin)": "bky_Latn",
    "Bolia (Latin)": "ble_Latn",
    "Baluan-Pam (Latin)": "blh_Latn",
    "Tai Dam (Latin)": "blt_Latn",
    "Mag-Indi Ayta (Latin)": "blx_Latn",
    "Balantak (Latin)": "blz_Latn",
    "Bembe (Latin)": "bmm_Latn",
    "Biao Mon (Latin)": "bmq_Latn",
    "Muinane (Latin)": "bmr_Latn",
    "Bomwali (Latin)": "bmu_Latn",
    "Bum (Latin)": "bmv_Latn",
    "Bangi (Bengali)": "bng_Beng",
    "Bonerif (Latin)": "bnm_Latn",
    "Bontok (Latin)": "bnn_Latn",
    "Bantoanon (Latin)": "bno_Latn",
    "Bola (Papua New Guinea) (Latin)": "bnp_Latn",
    "Bunun (Devanagari)": "bns_Deva",
    "Bora (Latin)": "boa_Latn",
    "Tibetan (Tibetan)": "bod_Tibt",
    "Anjam (Latin)": "boj_Latn",
    "Berom (Latin)": "bom_Latn",
    "Borôro (Latin)": "bor_Latn",
    "Bosnian (Latin)": "bos_Latn",
    "Bonkiman (Latin)": "bou_Latn",
    "Bongo (Latin)": "bov_Latn",
    "Tuwuli (Latin)": "box_Latn",
    "Barapasi (Latin)": "bpr_Latn",
    "Banda-Banda (Latin)": "bps_Latn",
    "Birgid (Latin)": "bqc_Latn",
    "Baga Pokur (Latin)": "bqg_Latn",
    "Bakhtiari (Arabic)": "bqi_Arab",
    "Banda-Mbrès (Latin)": "bqj_Latn",
    "Banda-Ndélé (Latin)": "bqp_Latn",
    "Braj (Devanagari)": "bra_Deva",
    "Breton (Latin)": "bre_Latn",
    "Brahui (Arabic)": "brh_Arab",
    "Bira (Congo) (Latin)": "bri_Latn",
    "Burui (Latin)": "bru_Latn",
    "Bodo (India) (Devanagari)": "brx_Deva",
    "Basa (Nigeria) (Latin)": "bsc_Latn",
    "Kati (Arabic)": "bsh_Arab",
    "Bangolan (Latin)": "bsj_Latn",
    "Burushaski (Latin)": "bsk_Latn",
    "Bassa-Kontagora (Latin)": "bsq_Latn",
    "Akoose (Latin)": "bss_Latn",
    "Busami (Latin)": "bsy_Latn",
    "Batak Dairi (Latin)": "btd_Latn",
    "Batak Mandailing (Latin)": "btm_Latn",
    "Ratte Buri (Latin)": "bts_Latn",
    "Bete-Bendi (Latin)": "btt_Latn",
    "Bateri (Arabic)": "btv_Arab",
    "Batak Karo (Latin)": "btx_Latn",
    "Budu (Latin)": "bud_Latn",
    "Buginese (Latin)": "bug_Latn",
    "Bulgarian (Cyrillic)": "bul_Cyrl",
    "Bulu (Cameroon) (Latin)": "bum_Latn",
    "Bulu (Cameroon) (Latin)": "buo_Latn",
    "Bussa (Latin)": "bus_Latn",
    "Bokobaru (Latin)": "bux_Latn",
    "Bube (Latin)": "bvb_Latn",
    "Baelelea (Latin)": "bvc_Latn",
    "Buriat (Latin)": "bvz_Latn",
    "Bwatoo (Latin)": "bwq_Latn",
    "Bura-Pabir (Latin)": "bwr_Latn",
    "Buli (Ghana) (Latin)": "bwu_Latn",
    "Bilur (Latin)": "bxf_Latn",
    "Buhutu (Latin)": "bxk_Latn",
    "Tiéyaxo Bozo (Latin)": "byc_Latn",
    "Bina (Nigeria) (Latin)": "byr_Latn",
    "Bisa (Latin)": "bys_Latn",
    "Batak (Latin)": "byv_Latn",
    "Qaqet (Latin)": "byx_Latn",
    "Blaan (Latin)": "bzh_Latn",
    "Bisu (Thai)": "bzi_Thai",
    "Jamaican Creole English (Latin)": "bzj_Latn",
    "Boano (Sulawesi) (Latin)": "bzw_Latn",
    "Chortí (Latin)": "caa_Latn",
    "Garifuna (Latin)": "cab_Latn",
    "Chuj (Latin)": "cac_Latn",
    "Kaqchikel (Latin)": "cak_Latn",
    "Carolinian (Latin)": "cap_Latn",
    "Galibi Carib (Latin)": "car_Latn",
    "Tsimané (Latin)": "cas_Latn",
    "Catalan (Latin)": "cat_Latn",
    "Cua (Latin)": "cax_Latn",
    "Cabiyarí (Latin)": "cbc_Latn",
    "Chachi (Latin)": "cbi_Latn",
    "Carijona (Latin)": "cbr_Latn",
    "Cashibo-Cacataibo (Latin)": "cbs_Latn",
    "Chayahuita (Latin)": "cbt_Latn",
    "Chachi (Latin)": "cbu_Latn",
    "Kakua (Latin)": "cbv_Latn",
    "Chopi (Latin)": "cce_Latn",
    "Samba Daka (Latin)": "ccg_Latn",
    "Chakma (Latin)": "cco_Latn",
    "Churahi (Devanagari)": "cdj_Deva",
    "Min Dong Chinese (Han)": "cdo_Hans",
    "Cebuano (Latin)": "ceb_Latn",
    "Cen Gbe (Latin)": "ceg_Latn",
    "Cek pet (Latin)": "cek_Latn",
    "Centúúm (Latin)": "cen_Latn",
    "Czech (Latin)": "ces_Latn",
    "Chafarruscas (Latin)": "cfa_Latn",
    "Falam Chin (Latin)": "cfm_Latn",
    "Chiga (Latin)": "cgg_Latn",
    "Chiga (Latin)": "cgg_Latn",
    "Chechen (Cyrillic)": "che_Cyrl",
    "Chontal de Tabasco (Latin)": "chf_Latn",
    "Chatino (Latin)": "chq_Latn",
    "Chuvash (Cyrillic)": "chv_Cyrl",
    "Ozumacín Chinantec (Latin)": "chz_Latn",
    "Chokwe (Latin)": "cjk_Latn",
    "Chamorro (Latin)": "cjo_Latn",
    "Upper Chehalis (Latin)": "cjp_Latn",
    "Shor (Cyrillic)": "cjs_Cyrl",
    "Central Kurdish (Arabic)": "ckb_Arab",
    "Cibak (Latin)": "ckl_Latn",
    "Anufo (Latin)": "cko_Latn",
    "Chak (Latin)": "ckr_Latn",
    "Chukot (Cyrillic)": "ckt_Cyrl",
    "Chukot (Latin)": "cky_Latn",
    "Chala (Latin)": "cla_Latn",
    "Lealao Chinantec (Latin)": "cle_Latn",
    "Eastern Highland Chatino (Latin)": "cly_Latn",
    "Mro-Khimi Chin (Latin)": "cme_Latn",
    "Mandarin Chinese (Han)": "cmn_Hans",
    "Mandarin Chinese (Han)": "cmn_Hant",
    "Central Mnong (Khmer)": "cmo_Khmr",
    "Central Mnong (Latin)": "cmo_Latn",
    "Mro-Khimi Chin (Latin)": "cmr_Latn",
    "Hakha Chin (Latin)": "cnh_Latn",
    "Ashéninka Pajonal (Latin)": "cni_Latn",
    "Lalana Chinantec (Latin)": "cnl_Latn",
    "Northern Tlaxiaco Chatino (Latin)": "cnt_Latn",
    "Cochimi (Latin)": "coe_Latn",
    "Cofán (Latin)": "cof_Latn",
    "Chong (Latin)": "cok_Latn",
    "Cotoname (Latin)": "con_Latn",
    "Cornish (Latin)": "cor_Latn",
    "Caquinte (Latin)": "cot_Latn",
    "Wamey (Latin)": "cou_Latn",
    "Ponares (Latin)": "cpa_Latn",
    "Ucayali-Yurúa Ashéninka (Latin)": "cpb_Latn",
    "Pichis Ashéninka (Latin)": "cpu_Latn",
    "Pu-Xian Chinese (Han)": "cpx_Hans",
    "Ucayali-Yurúa Ashéninka (Latin)": "cpy_Latn",
    "Crimean Tatar (Cyrillic)": "crh_Cyrl",
    "Cree (Canadian Aboriginal Syllabics)": "crk_Cans",
    "Cree (Latin)": "crk_Latn",
    "El Nayar Cora (Latin)": "crn_Latn",
    "Caramanta (Latin)": "crq_Latn",
    "Seselwa Creole French (Latin)": "crs_Latn",
    "Iyo'wujwa Chorote (Latin)": "crt_Latn",
    "Carrier (Latin)": "csk_Latn",
    "Southern Ping Chinese (Latin)": "cso_Latn",
    "Northern Tlaxiaco Chatino (Latin)": "ctd_Latn",
    "Tepinapa Chinantec (Latin)": "cte_Latn",
    "Chittagonian (Bengali)": "ctg_Beng",
    "Tataltepec Chatino (Latin)": "ctl_Latn",
    "Tataltepec Chatino (Latin)": "cto_Latn",
    "Wayanad Chetti (Latin)": "ctu_Latn",
    "Cun (Latin)": "cuc_Latn",
    "Culina (Latin)": "cui_Latn",
    "Culina (Latin)": "cuk_Latn",
    "Culina (Latin)": "cul_Latn",
    "Teutila Cuicatec (Latin)": "cut_Latn",
    "Chuka (Latin)": "cux_Latn",
    "Chuwabu (Latin)": "cwa_Latn",
    "Kwere (Latin)": "cwe_Latn",
    "Nute (Latin)": "cwt_Latn",
    "Cemuhî (Latin)": "cya_Latn",
    "Welsh (Latin)": "cym_Latn",
    "Dambi (Latin)": "daa_Latn",
    "Dagbani (Latin)": "dag_Latn",
    "Gwahatike (Latin)": "dah_Latn",
    "Danish (Latin)": "dan_Latn",
    "Dargwa (Cyrillic)": "dar_Cyrl",
    "Taita (Latin)": "dav_Latn",
    "Dabarre (Latin)": "dbd_Latn",
    "Doga (Latin)": "dbj_Latn",
    "Daba (Latin)": "dbq_Latn",
    "Deccan (Arabic)": "dcc_Arab",
    "Dendi (Nigeria) (Latin)": "ddn_Latn",
    "Dedua (Latin)": "ded_Latn",
    "Dezfuli (Latin)": "deg_Latn",
    "Desano (Latin)": "des_Latn",
    "German (Latin)": "deu_Latn",
    "Dagaari Dioula (Latin)": "dga_Latn",
    "Dghwede (Latin)": "dgh_Latn",
    "Dugwor (Latin)": "dgi_Latn",
    "Dakka (Latin)": "dgk_Latn",
    "Dogri (macrolanguage) (Devanagari)": "dgo_Deva",
    "Dogrib (Latin)": "dgr_Latn",
    "Didinga (Devanagari)": "dhi_Deva",
    "Digo (Latin)": "did_Latn",
    "Digo (Latin)": "dig_Latn",
    "Dilling (Latin)": "dik_Latn",
    "Dilling (Latin)": "dip_Latn",
    "Dhivehi (Thaana)": "div_Thaa",
    "Zarma (Latin)": "dje_Latn",
    "Jukun of Takum (Latin)": "djk_Latn",
    "Domaaki (Arabic)": "dmk_Arab",
    "Domaaki (Arabic)": "dml_Arab",
    "Dan (Latin)": "dnj_Latn",
    "Dan (Latin)": "dnt_Latn",
    "Dan (Latin)": "dnw_Latn",
    "Dom (Latin)": "dop_Latn",
    "Dogosé (Latin)": "dos_Latn",
    "Duruwa (Latin)": "dru_Latn",
    "Lower Sorbian (Latin)": "dsb_Latn",
    "Daasanach (Latin)": "dsh_Latn",
    "Dusner (Latin)": "dtp_Latn",
    "Toro So Dogon (Latin)": "dts_Latn",
    "Dotyali (Devanagari)": "dty_Deva",
    "Duala (Latin)": "dua_Latn",
    "Duna (Latin)": "dug_Latn",
    "Dutton World Speedwords (Latin)": "dwr_Latn",
    "Dyiri (Latin)": "dyi_Latn",
    "Dyola-Fonyi (Latin)": "dyo_Latn",
    "Dyula (Latin)": "dyu_Latn",
    "Dazaga (Latin)": "dzg_Latn",
    "Dzongkha (Tibetan)": "dzo_Tibt",
    "Embu (Latin)": "ebu_Latn",
    "Epie (Latin)": "ego_Latn",
    "Eipomek (Latin)": "eip_Latn",
    "Askopan (Latin)": "eiv_Latn",
    "Eka (Latin)": "eka_Latn",
    "Standard Estonian (Latin)": "ekk_Latn",
    "Eki (Latin)": "eko_Latn",
    "Yace (Latin)": "ekr_Latn",
    "Modern Greek (1453-) (Greek)": "ell_Grek",
    "Modern Greek (1453-) (Greek, cypr1249)": "ell_Grek_cypr1249",
    "Eleme (Latin)": "elm_Latn",
    "Eman (Latin)": "emp_Latn",
    "Enlhet (Latin)": "enb_Latn",
    "English (Latin)": "eng_Latn",
    "Enxet (Latin)": "enx_Latn",
    "Esperanto (Latin)": "epo_Latn",
    "Ese Ejja (Latin)": "ese_Latn",
    "Esselen (Latin)": "ess_Latn",
    "Central Yupik (Latin)": "esu_Latn",
    "Eton (Vanuatu) (Latin)": "eto_Latn",
    "Eton (Cameroon) (Latin)": "ets_Latn",
    "Eton (Cameroon) (Latin)": "etu_Latn",
    "Basque (Latin)": "eus_Latn",
    "Even (Cyrillic)": "evn_Cyrl",
    "Ewe (Latin)": "ewe_Latn",
    "Ewondo (Latin)": "ewo_Latn",
    "Eyak (Latin)": "eyo_Latn",
    "Ezaa (Latin)": "eza_Latn",
    "Fali (Latin)": "fal_Latn",
    "Fang (Equatorial Guinea) (Latin)": "fan_Latn",
    "Faroese (Latin)": "fao_Latn",
    "Fasu (Latin)": "far_Latn",
    "Persian (Arabic)": "fas_Arab",
    "Fanti (Latin)": "fat_Latn",
    "Faita (Latin)": "fia_Latn",
    "Fijian (Latin)": "fij_Latn",
    "Filipino (Latin)": "fil_Latn",
    "Finnish (Latin)": "fin_Latn",
    "Fipa (Latin)": "fip_Latn",
    "Knaanic (Latin)": "fkk_Latn",
    "Foau (Latin)": "flr_Latn",
    "Fe'fe' (Latin)": "fmp_Latn",
    "Far Western Muria (Devanagari)": "fmu_Deva",
    "Fon (Latin)": "fon_Latn",
    "French (Latin)": "fra_Latn",
    "Fordata (Latin)": "frd_Latn",
    "Western Frisian (Latin)": "fry_Latn",
    "Fulah (Latin)": "fub_Latn",
    "Pulaar (Latin)": "fuc_Latn",
    "East Futuna (Latin)": "fue_Latn",
    "Fulah (Latin)": "ful_Latn",
    "Pulaar (Latin)": "fuq_Latn",
    "Nigerian Fulfulde (Latin)": "fuv_Latn",
    "Gagauz (Cyrillic)": "gag_Cyrl",
    "Gagauz (Latin)": "gag_Latn",
    "Gaina (Latin)": "gai_Latn",
    "Gamkonora (Latin)": "gam_Latn",
    "Kandawo (Telugu)": "gau_Telu",
    "Gabri (Latin)": "gbi_Latn",
    "Kaytetye (Devanagari)": "gbk_Deva",
    "Garhwali (Devanagari)": "gbm_Deva",
    "Gbari (Latin)": "gbo_Latn",
    "Gbagyi (Latin)": "gbr_Latn",
    "Gbagyi (Latin)": "gby_Latn",
    "Alekano (Latin)": "gcc_Latn",
    "Gade (Latin)": "gde_Latn",
    "Guduf-Gava (Latin)": "gdf_Latn",
    "Gengle (Latin)": "geb_Latn",
    "Gebe (Latin)": "gej_Latn",
    "Geser-Gorom (Latin)": "ges_Latn",
    "Guria (Arabic)": "ggg_Arab",
    "Gidar (Latin)": "gid_Latn",
    "Gbazari (Arabic)": "gig_Arab",
    "Gilbertese (Latin)": "gil_Latn",
    "Gimi (Papua New Guinea) (Latin)": "giz_Latn",
    "Kachi Koli (Arabic)": "gjk_Arab",
    "Gunditjmara (Latin)": "gjn_Latn",
    "Gujari (Arabic)": "gju_Arab",
    "Gokana (Latin)": "gkn_Latn",
    "Nanai (Cyrillic)": "gld_Cyrl",
    "Irish (Latin)": "gle_Latn",
    "Galician (Latin)": "glg_Latn",
    "Gilaki (Arabic)": "glk_Arab",
    "Manx (Latin)": "glv_Latn",
    "Gula (Chad) (Latin)": "glw_Latn",
    "Gamo (Latin)": "gmv_Latn",
    "Gana (Latin)": "gna_Latn",
    "Gondi (Latin)": "gnd_Latn",
    "Ngangam (Latin)": "gng_Latn",
    "Gofa (Latin)": "gof_Latn",
    "Gogo (Latin)": "gog_Latn",
    "Gola (Latin)": "gol_Latn",
    "Goan Konkani (Devanagari)": "gom_Deva",
    "Gorontalo (Latin)": "gor_Latn",
    "Gor (Latin)": "gqr_Latn",
    "Ancient Greek (to 1453) (Greek)": "grc_Grek",
    "Gbiri-Niragu (Latin)": "gri_Latn",
    "Guarani (Latin)": "grn_Latn",
    "Garo (Bengali)": "grt_Beng",
    "Guriaso (Latin)": "gsl_Latn",
    "German Sign Language (Latin)": "gso_Latn",
    "Guajajára (Latin)": "gub_Latn",
    "Wayuu (Latin)": "guc_Latn",
    "Yocoboué Dida (Latin)": "gud_Latn",
    "Paraguayan Guaraní (Latin)": "gug_Latn",
    "Guahibo (Latin)": "guh_Latn",
    "Eastern Bolivian Guaraní (Latin)": "gui_Latn",
    "Gujarati (Gujarati)": "guj_Gujr",
    "Gumuz (Ethiopic)": "guk_Ethi",
    "Gumuz (Latin)": "gum_Latn",
    "Guro (Latin)": "guo_Latn",
    "Guinau dan (Latin)": "guq_Latn",
    "Farefare (Latin)": "gur_Latn",
    "Farefare (Latin)": "guu_Latn",
    "Gusilay (Latin)": "gux_Latn",
    "Gusii (Latin)": "guz_Latn",
    "Guanano (Latin)": "gvc_Latn",
    "Gwanja (Latin)": "gvl_Latn",
    "Kalami (Arabic)": "gwc_Arab",
    "Gweno (Latin)": "gwe_Latn",
    "Gwichʼin (Latin)": "gwi_Latn",
    "Gwere (Latin)": "gwr_Latn",
    "Gwere (Arabic)": "gwt_Arab",
    "Guaymí (Latin)": "gym_Latn",
    "Gyem (Latin)": "gyr_Latn",
    "Geji (Latin)": "gyz_Latn",
    "Hadiyya (Latin)": "had_Latn",
    "Hanga (Latin)": "hag_Latn",
    "Hahon (Latin)": "hah_Latn",
    "Hakka Chinese (Latin)": "hak_Latn",
    "Ha(Latin)": "hao_Latn",
    "Hdi (Latin)": "hap_Latn",
    "Haitian (Latin)": "hat_Latn",
    "Hausa (Latin)": "hau_Latn",
    "Hawaiian (Latin)": "haw_Latn",
    "Haya (Latin)": "hay_Latn",
    "Huba (Latin)": "hbb_Latn",
    "Huichol (Latin)": "hch_Latn",
    "Hebrew (Hebrew)": "heb_Hebr",
    "Hehe (Latin)": "heh_Latn",
    "Herero (Latin)": "her_Latn",
    "Hiaitsiihi (Latin)": "hia_Latn",
    "Fiji Hindi (Latin)": "hif_Latn",
    "Higgi (Latin)": "hig_Latn",
    "Hiligaynon (Latin)": "hil_Latn",
    "Hindi (Devanagari)": "hin_Deva",
    "Hkongso Chin (Latin)": "hkk_Latn",
    "Halang (Latin)": "hla_Latn",
    "Halia (Devanagari)": "hlb_Deva",
    "Matu Chin (Latin)": "hlt_Latn",
    "Chhattisgarhi (Devanagari)": "hne_Deva",
    "Hän (Latin)": "hnn_Latn",
    "Northern Hindko (Arabic)": "hno_Arab",
    "Hunsrik (Latin)": "hns_Latn",
    "Ho (Oriya)": "hoc_Orya",
    "Croatian (Latin)": "hrv_Latn",
    "Upper Sorbian (Latin)": "hsb_Latn",
    "Hoti (Latin)": "hto_Latn",
    "Huba (Latin)": "hub_Latn",
    "Huave (Latin)": "hue_Latn",
    "San Francisco Del Mar Huave (Latin)": "hui_Latn",
    "Hula (Latin)": "hul_Latn",
    "Hungarian (Latin)": "hun_Latn",
    "Huastec (Latin)": "hus_Latn",
    "Humla (Latin)": "huu_Latn",
    "San Mateo Del Mar Huave (Latin)": "huv_Latn",
    "Hulaulá (Latin)": "hux_Latn",
    "Havanese (Latin)": "hvn_Latn",
    "Hwana (Latin)": "hwo_Latn",
    "Armenian (Armenian)": "hye_Armn",
    "Western Armenian (Armenian)": "hyw_Armn",
    "Iban (Latin)": "iba_Latn",
    "Ibibio (Latin)": "ibb_Latn",
    "Igbo (Latin)": "ibo_Latn",
    "Etkywan (Latin)": "icr_Latn",
    "Ido (Latin)": "ida_Latn",
    "Idon (Latin)": "idd_Latn",
    "Idoma (Latin)": "idu_Latn",
    "Ifugao (Latin)": "ifa_Latn",
    "Amganad Ifugao (Latin)": "ifb_Latn",
    "Ifo (Latin)": "ife_Latn",
    "Tuwali Ifugao (Latin)": "ifk_Latn",
    "Mayoyao Ifugao (Latin)": "ifu_Latn",
    "Keley-I Kallahan (Latin)": "ify_Latn",
    "Igede (Latin)": "igl_Latn",
    "Igala (Latin)": "ign_Latn",
    "Ijaw (Latin)": "ijc_Latn",
    "Biseni (Latin)": "ijn_Latn",
    "Ika (Latin)": "ikk_Latn",
    "Ikwere (Latin)": "ikw_Latn",
    "Ila (Latin)": "ilb_Latn",
    "Ilocano (Latin)": "ilo_Latn",
    "Imbongu (Latin)": "imo_Latn",
    "Interlingua (International Auxiliary Language Association) (Latin)": "ina_Latn",
    "Inga (Latin)": "inb_Latn",
    "Indonesian (Latin)": "ind_Latn",
    "Iu Mien (Latin)": "iou_Latn",
    "Ipili (Latin)": "ipi_Latn",
    "Inupiaq (Latin)": "ipk_Latn",
    "Iquito (Latin)": "iqw_Latn",
    "Iresim (Latin)": "iri_Latn",
    "Irarutu (Latin)": "irk_Latn",
    "Isekiri (Latin)": "ish_Latn",
    "Icelandic (Latin)": "isl_Latn",
    "Isoko (Latin)": "iso_Latn",
    "Italian (Latin)": "ita_Latn",
    "Itelmen (Cyrillic)": "itl_Cyrl",
    "Isekiri (Latin)": "its_Latn",
    "Isekiri (Latin)": "itv_Latn",
    "Ito (Latin)": "itw_Latn",
    "Itzá (Latin)": "itz_Latn",
    "Ixil (Latin)": "ixl_Latn",
    "Izere (Latin)": "izr_Latn",
    "Izii (Latin)": "izz_Latn",
    "Jakaltek (Latin)": "jac_Latn",
    "Yalahatan (Latin)": "jal_Latn",
    "Jamaican Creole English (Latin)": "jam_Latn",
    "Javanese (Latin)": "jav_Latn",
    "Jambi Malay (Latin)": "jax_Latn",
    "Jibu (Latin)": "jbu_Latn",
    "Jerung (Latin)": "jen_Latn",
    "Jicaque (Latin)": "jic_Latn",
    "Jivaro (Latin)": "jiv_Latn",
    "Machame (Latin)": "jmc_Latn",
    "Zumbun (Latin)": "jmd_Latn",
    "Jimi (Nigeria) (Latin)": "jmx_Latn",
    "Japanese (Japanese)": "jpn_Jpan",
    "Jaqaru (Latin)": "jqr_Latn",
    "Jowulu (Latin)": "juk_Latn",
    "Ju'hoan (Oriya)": "jun_Orya",
    "Juang (Latin)": "juo_Latn",
    "Wapan (Latin)": "jvn_Latn",
    "Kara-Kalpak (Cyrillic)": "kaa_Cyrl",
    "Kabyle (Latin)": "kab_Latn",
    "Kachin (Latin)": "kac_Latn",
    "Gayo (Latin)": "kai_Latn",
    "Jju (Latin)": "kaj_Latn",
    "Jju (Latin)": "kak_Latn",
    "Kamba (Kenya) (Latin)": "kam_Latn",
    "Kannada (Kannada)": "kan_Knda",
    "Kanu (Latin)": "kao_Latn",
    "Bezhta (Latin)": "kaq_Latn",
    "Kashmiri (Arabic)": "kas_Arab",
    "Georgian (Georgian)": "kat_Geor",
    "Kadazan Dusun (Latin)": "kay_Latn",
    "Kazakh (Cyrillic)": "kaz_Cyrl",
    "Kabardian (Cyrillic)": "kbd_Cyrl",
    "Kayan (Latin)": "kbl_Latn",
    "Kande (Latin)": "kbo_Latn",
    "Kabiye (Latin)": "kbp_Latn",
    "Kabiye (Latin)": "kbq_Latn",
    "Kafa (Latin)": "kbr_Latn",
    "Kamo (Latin)": "kbt_Latn",
    "Kikuyu (Latin)": "kby_Latn",
    "Ket (Cyrillic)": "kca_Cyrl",
    "Tyap (Latin)": "kcg_Latn",
    "Kono (Nigeria) (Latin)": "kcn_Latn",
    "Kutu (Latin)": "kcq_Latn",
    "Kutu (Latin)": "kdc_Latn",
    "Makonde (Latin)": "kde_Latn",
    "Tem (Latin)": "kdh_Latn",
    "Kumam (Latin)": "kdi_Latn",
    "Kumam (Latin)": "kdj_Latn",
    "Tsikimba (Latin)": "kdl_Latn",
    "Kagulu (Latin)": "kdn_Latn",
    "Kuy (Khmer)": "kdt_Khmr",
    "Kepo' (Latin)": "kea_Latn",
    "Kekchi (Latin)": "kek_Latn",
    "Kenyang (Latin)": "ken_Latn",
    "Kenyah (Latin)": "keo_Latn",
    "Kera (Latin)": "ker_Latn",
    "Kugbo (Latin)": "keu_Latn",
    "Komi-Permyak (Telugu)": "key_Telu",
    "Kukele (Latin)": "kez_Latn",
    "Kobiana (Devanagari)": "kfb_Deva",
    "Northwestern Kolami (Telugu)": "kff_Telu",
    "Kuk (Devanagari)": "kfk_Deva",
    "Kotaba (Devanagari)": "kfq_Deva",
    "Koya (Gujarati)": "kfr_Gujr",
    "Koro (India) (Latin)": "kfw_Latn",
    "Kaili (Devanagari)": "kfx_Deva",
    "Khasi (Latin)": "kha_Latn",
    "Kham (Tibetan)": "khg_Tibt",
    "Khalkha Mongolian (Cyrillic)": "khk_Cyrl",
    "Khmer (Khmer)": "khm_Khmr",
    "Koyra Chiini Songhay (Latin)": "khq_Latn",
    "Khowar (Arabic)": "khw_Arab",
    "Kim (Latin)": "kia_Latn",
    "Koalib (Latin)": "kij_Latn",
    "Kikuyu (Latin)": "kik_Latn",
    "Kinyarwanda (Latin)": "kin_Latn",
    "Kirghiz (Cyrillic)": "kir_Cyrl",
    "Kitharaka (Latin)": "kix_Latn",
    "Mlap (Latin)": "kjb_Latn",
    "Coastal Konjo (Latin)": "kjc_Latn",
    "Kisar (Latin)": "kje_Latn",
    "Khmu (Latin)": "kjg_Latn",
    "Khakas (Cyrillic)": "kjh_Cyrl",
    "Khakas (Latin)": "kjk_Latn",
    "Kagulu (Latin)": "kki_Latn",
    "Kikuyu (Latin)": "kkj_Latn",
    "Kalanguya (Devanagari)": "kle_Deva",
    "Kalenjin (Latin)": "kln_Latn",
    "Kulisusu (Latin)": "kls_Latn",
    "Klao (Latin)": "klu_Latn",
    "Maskelynes (Latin)": "klv_Latn",
    "Tado (Latin)": "klw_Latn",
    "Kama (Latin)": "kma_Latn",
    "Kimbundu (Latin)": "kmd_Latn",
    "Tanudan Kalinga (Latin)": "kml_Latn",
    "Northern Kurdish (Arabic)": "kmr_Arab",
    "Northern Kurdish (Cyrillic)": "kmr_Cyrl",
    "Northern Kurdish (Latin)": "kmr_Latn",
    "Kanite (Latin)": "kmu_Latn",
    "Koma (Latin)": "kmy_Latn",
    "Kanda (Latin)": "kna_Latn",
    "Lubuagan Kalinga (Latin)": "knb_Latn",
    "Central Kanuri (Latin)": "knc_Latn",
    "Kankanaey (Latin)": "kne_Latn",
    "Kutu (Latin)": "knf_Latn",
    "Konda (Latin)": "knj_Latn",
    "Kuranko (Latin)": "knk_Latn",
    "Konkani (macrolanguage) (Devanagari)": "knn_Deva",
    "Kono (Sierra Leone) (Latin)": "kno_Latn",
    "Kongo (Latin)": "kog_Latn",
    "Kol (Papua New Guinea) (Latin)": "kol_Latn",
    "Konzo (Latin)": "koo_Latn",
    "Korean (Hangul)": "kor_Hang",
    "Kodia (Latin)": "kpo_Latn",
    "Korupun-Sela (Latin)": "kpq_Latn",
    "Kofei (Latin)": "kps_Latn",
    "Komi-Zyrian (Cyrillic)": "kpv_Cyrl",
    "Komi-Permyak (Cyrillic)": "kpy_Cyrl",
    "Kofyar (Latin)": "kpz_Latn",
    "Korafe-Yegha (Latin)": "kqe_Latn",
    "Korafe-Yegha (Latin)": "kqo_Latn",
    "Kimré (Latin)": "kqp_Latn",
    "Kimaragang (Latin)": "kqr_Latn",
    "Koyra Chiini Songhay (Ethiopic)": "kqy_Ethi",
    "Karachay-Balkar (Cyrillic)": "krc_Cyrl",
    "Krio (Latin)": "kri_Latn",
    "Kinaray-A (Latin)": "krj_Latn",
    "Karelian (Latin)": "krl_Latn",
    "Sapo (Khmer)": "krr_Khmr",
    "Gbaya (Sudan) (Latin)": "krs_Latn",
    "Kurukh (Devanagari)": "kru_Deva",
    "Tewa (Indonesia) (Latin)": "krx_Latn",
    "Shambala (Latin)": "ksb_Latn",
    "Kuanua (Latin)": "ksd_Latn",
    "Bafia (Latin)": "ksf_Latn",
    "Krisa (Latin)": "ksr_Latn",
    "Kusasi (Latin)": "kss_Latn",
    "Kham (Devanagari)": "ksz_Deva",
    "Kambaata (Ethiopic)": "ktb_Ethi",
    "Krumen (Latin)": "ktj_Latn",
    "Kto (Latin)": "kto_Latn",
    "Kuanyama (Latin)": "kua_Latn",
    "Kutep (Latin)": "kub_Latn",
    "Kuman (Papua New Guinea) (Latin)": "kue_Latn",
    "Kushi (Latin)": "kuh_Latn",
    "Kumyk (Cyrillic)": "kum_Cyrl",
    "Kurdish (Arabic)": "kur_Arab",
    "Kusaal (Latin)": "kus_Latn",
    "Kutino (Latin)": "kvn_Latn",
    "Kove (Latin)": "kvw_Latn",
    "Komi (Arabic)": "kvx_Arab",
    "Kutu (Latin)": "kwd_Latn",
    "Kwara'ae (Latin)": "kwf_Latn",
    "Awa-Cuaiquer (Latin)": "kwi_Latn",
    "Kwak'wala (Latin)": "kwm_Latn",
    "Kodia (Ethiopic)": "kxc_Ethi",
    "Maninkakan, Kita (Latin)": "kxf_Latn",
    "Kuanhua (Thai)": "kxm_Thai",
    "Wadiyara Koli (Arabic)": "kxp_Arab",
    "Kwaya (Latin)": "kyb_Latn",
    "Kyaka (Latin)": "kyc_Latn",
    "Karey (Latin)": "kyf_Latn",
    "Keyagana (Latin)": "kyg_Latn",
    "Kouya (Latin)": "kyo_Latn",
    "Kwaya (Latin)": "kyq_Latn",
    "Kayagar (Kayah Li)": "kyu_Kali",
    "Kambaira (Latin)": "kyx_Latn",
    "Kerewo (Latin)": "kyz_Latn",
    "Kairiru (Latin)": "kzf_Latn",
    "Kelabit (Latin)": "kzi_Latn",
    "Lacandon (Latin)": "lac_Latn",
    "Langi (Latin)": "lag_Latn",
    "Lango (Uganda) (Latin)": "laj_Latn",
    "Lamba (Latin)": "lam_Latn",
    "Lao (Lao)": "lao_Laoo",
    "Lama (Togo) (Latin)": "las_Latn",
    "Latin (Latin)": "lat_Latn",
    "Latvian (Latin)": "lav_Latn",
    "Lavu (Latin)": "law_Latn",
    "Lama (Myanmar) (Tibetan)": "lbj_Tibt",
    "Lachi (Latin)": "lbw_Latn",
    "Luchazi (Latin)": "lcm_Latn",
    "Lola (Thai)": "lcp_Thai",
    "Lidzonka (Latin)": "ldb_Latn",
    "Leko (Latin)": "led_Latn",
    "Lyélé (Latin)": "lee_Latn",
    "Lefa (Latin)": "lef_Latn",
    "Lembena (Latin)": "lem_Latn",
    "Lense (Latin)": "lew_Latn",
    "Lemio (Latin)": "lex_Latn",
    "Lega-Shabunda (Latin)": "lgg_Latn",
    "Laghu (Latin)": "lgl_Latn",
    "Lahu (Latin)": "lhu_Latn",
    "Lianshan Zhuang (Latin)": "lia_Latn",
    "Likum (Latin)": "lid_Latn",
    "Limbu (Devanagari)": "lif_Deva",
    "Ligurian (Latin)": "lij_Latn",
    "Lingala (Latin)": "lin_Latn",
    "Liki (Latin)": "lip_Latn",
    "Libinza (Latin)": "lir_Latn",
    "Lisu (Lisu)": "lis_Lisu",
    "Lithuanian (Latin)": "lit_Latn",
    "Rampi (Latin)": "lje_Latn",
    "Lampung Api (Latin)": "ljp_Latn",
    "Lukabaras (Latin)": "lkb_Latn",
    "Lakata (Latin)": "lke_Latn",
    "Lilau (Latin)": "lla_Latn",
    "Ladin (Latin, gherd)": "lld_Latn_gherd",
    "Ladin (Latin, valbadia)": "lld_Latn_valbadia",
    "Láá Láá Bwamu (Latin)": "llg_Latn",
    "Lele (Guinea) (Latin)": "lln_Latn",
    "Loma (Liberia) (Latin)": "lme_Latn",
    "Lundayeh (Latin)": "lnd_Latn",
    "Lango (South Sudan) (Latin)": "lns_Latn",
    "Lundayeh (Latin)": "lnu_Latn",
    "Loloda (Latin)": "loa_Latn",
    "Lobi (Latin)": "lob_Latn",
    "Loko (Latin)": "lok_Latn",
    "Loma (Liberia) (Latin)": "lom_Latn",
    "Loma (Liberia) (Latin)": "lon_Latn",
    "Lobala (Latin)": "loq_Latn",
    "Luri (Arabic)": "lrk_Arab",
    "Lish (Latin)": "lsi_Latn",
    "Sa'ban (Latin)": "lsm_Latn",
    "Sa'ban (Arabic)": "lss_Arab",
    "Latgalian (Latin)": "ltg_Latn",
    "Lethu (Latin)": "lth_Latn",
    "Lutachoni (Latin)": "lto_Latn",
    "Luxembourgish (Latin)": "ltz_Latn",
    "Luba-Lulua (Latin)": "lua_Latn",
    "Aringa (Latin)": "luc_Latn",
    "Ganda (Latin)": "lug_Latn",
    "Luo (Kenya and Tanzania) (Latin)": "luo_Latn",
    "Lushai (Latin)": "lus_Latn",
    "Luwanga (Latin)": "lwg_Latn",
    "Lwo (Latin)": "lwo_Latn",
    "Lewo Eleng (Latin)": "lww_Latn",
    "Laz (Latin)": "lzz_Latn",
    "Maasai (Latin)": "maa_Latn",
    "Yutanduchi Mixtec (Latin)": "mab_Latn",
    "Madurese (Latin)": "mad_Latn",
    "Mafa (Latin)": "maf_Latn",
    "Magahi (Devanagari)": "mag_Deva",
    "Marshallese (Latin)": "mah_Latn",
    "Maithili (Devanagari)": "mai_Deva",
    "Majhwar (Latin)": "maj_Latn",
    "Makasar (Latin)": "mak_Latn",
    "Malayalam (Malayalam)": "mal_Mlym",
    "Mam (Latin)": "mam_Latn",
    "Mamaindé (Latin)": "maq_Latn",
    "Marathi (Devanagari)": "mar_Deva",
    "Mazatec (Latin)": "mau_Latn",
    "Sateré-Mawé (Latin)": "maw_Latn",
    "North Moluccan Malay (Latin)": "max_Latn",
    "Central Mazahua (Latin)": "maz_Latn",
    "Western Bukidnon Manobo (Latin)": "mbb_Latn",
    "Macushi (Latin)": "mbc_Latn",
    "Duna (Latin)": "mbh_Latn",
    "Ilianen Manobo (Latin)": "mbj_Latn",
    "Matigsalug Manobo (Latin)": "mbt_Latn",
    "Mbo (Cameroon) (Latin)": "mbu_Latn",
    "Macuna (Latin)": "mca_Latn",
    "Machiguenga (Latin)": "mcb_Latn",
    "Bitur (Latin)": "mcd_Latn",
    "Matsés (Latin)": "mcf_Latn",
    "Mixe (Latin)": "mco_Latn",
    "Ese (Latin)": "mcp_Latn",
    "M seri (Latin)": "mcq_Latn",
    "Mambai (Latin)": "mcu_Latn",
    "Mpiemo (Latin)": "mcx_Latn",
    "Mada (Nigeria) (Latin)": "mda_Latn",
    "Morigi (Latin)": "mdd_Latn",
    "Mbosi (Latin)": "mdv_Latn",
    "Male (Ethiopia) (Ethiopic)": "mdy_Ethi",
    "Medumba (Latin)": "med_Latn",
    "Melpa (Latin)": "mee_Latn",
    "Southwestern Tlaxiaco Mixtec (Latin)": "meh_Latn",
    "Midob (Latin)": "mej_Latn",
    "Mekeo (Latin)": "mek_Latn",
    "Central Melanau (Latin)": "mel_Latn",
    "Mende (Liberia) (Latin)": "men_Latn",
    "Merey (Latin)": "meq_Latn",
    "Meru (Latin)": "mer_Latn",
    "Mato (Latin)": "met_Latn",
    "Motu (Latin)": "meu_Latn",
    "Mano (Latin)": "mev_Latn",
    "Morisyen (Latin)": "mfe_Latn",
    "Mefele (Latin)": "mfh_Latn",
    "Mefele (Latin)": "mfi_Latn",
    "Mogofin (Latin)": "mfk_Latn",
    "Cross River Mbembe (Latin)": "mfm_Latn",
    "Mefele (Latin)": "mfn_Latn",
    "Mbe (Latin)": "mfo_Latn",
    "Marghi South (Latin)": "mfq_Latn",
    "Marghi (Latin)": "mfv_Latn",
    "Pahi (Latin)": "mfy_Latn",
    "Melo (Latin)": "mfz_Latn",
    "Maguindanaon (Latin)": "mgd_Latn",
    "Mpade (Latin)": "mge_Latn",
    "Monguor (Latin)": "mgg_Latn",
    "Makhuwa-Meetto (Latin)": "mgh_Latn",
    "Laua (Latin)": "mgi_Latn",
    "Meta' (Latin)": "mgo_Latn",
    "Ma'di (Latin)": "mhi_Latn",
    "Mouk-Aria (Latin)": "mhk_Latn",
    "Mari (Russia) (Cyrillic)": "mhr_Cyrl",
    "Mundat (Latin)": "mhu_Latn",
    "Maru (Latin)": "mhx_Latn",
    "Ma'di (Latin)": "mhy_Latn",
    "Atatláhuca Mixtec (Latin)": "mib_Latn",
    "Mi'kmaq (Latin)": "mie_Latn",
    "Mofu-Gudur (Latin)": "mif_Latn",
    "San Miguel El Grande Mixtec (Latin)": "mig_Latn",
    "Chayuco Mixtec (Latin)": "mih_Latn",
    "Peñoles Mixtec (Latin)": "mil_Latn",
    "Alacatlatzala Mixtec (Latin)": "mim_Latn",
    "Minangkabau (Latin)": "min_Latn",
    "Pinotepa Nacional Mixtec (Latin)": "mio_Latn",
    "Apasco-Apoala Mixtec (Latin)": "mip_Latn",
    "Mískito (Latin)": "miq_Latn",
    "Mískito (Latin)": "mit_Latn",
    "Southern Puebla Mixtec (Latin)": "miu_Latn",
    "Akoye (Latin)": "miy_Latn",
    "Coatzospan Mixtec (Latin)": "miz_Latn",
    "Mali (Devanagari)": "mjl_Deva",
    "Malavedan (Malayalam)": "mjv_Mlym",
    "Macedonian (Cyrillic)": "mkd_Cyrl",
    "Mokole (Benin) (Latin)": "mkf_Latn",
    "Dhatki (Arabic)": "mki_Arab",
    "Mokole (Benin) (Latin)": "mkl_Latn",
    "Mokole (Benin) (Latin)": "mkn_Latn",
    "Malagasy (Latin)": "mlg_Latn",
    "Maltese (Latin)": "mlq_Latn",
    "Maltese (Latin)": "mlt_Latn",
    "Mamanwa (Latin)": "mmc_Latn",
    "Michoacán Mazahua (Latin)": "mmg_Latn",
    "Maonan (Latin)": "mnb_Latn",
    "Montenegrin (Latin)": "mne_Latn",
    "Mundani (Latin)": "mnf_Latn",
    "Manipuri (Bengali)": "mni_Beng",
    "Maninka (Latin)": "mnk_Latn",
    "Mon (Myanmar)": "mnw_Mymr",
    "Manikion (Latin)": "mnx_Latn",
    "Mwan (Latin)": "moa_Latn",
    "Mogholi (Latin)": "mog_Latn",
    "Mongolian (Cyrillic)": "mon_Cyrl",
    "Mopán Maya (Latin)": "mop_Latn",
    "Mor (New Guinea) (Latin)": "mor_Latn",
    "Mossi (Latin)": "mos_Latn",
    "Tucunaca (Latin)": "mox_Latn",
    "Mukulu (Latin)": "moz_Latn",
    "Mpompon (Latin)": "mpg_Latn",
    "Yosondúa Mixtec (Latin)": "mpm_Latn",
    "Mapidian (Latin)": "mpp_Latn",
    "Mixtec (Latin)": "mpx_Latn",
    "Malas (Latin)": "mqb_Latn",
    "Mangole (Latin)": "mqf_Latn",
    "Minokok (Latin)": "mqj_Latn",
    "Mumuye (Latin)": "mqn_Latn",
    "Manggarai (Latin)": "mqy_Latn",
    "Maori (Latin)": "mri_Latn",
    "Western Mari (Cyrillic)": "mrj_Cyrl",
    "Western Magar (Devanagari)": "mrr_Deva",
    "Maranao (Latin)": "mrt_Latn",
    "Maru (Latin)": "mrw_Latn",
    "Masaba (Latin)": "msh_Latn",
    "Sabah Malay (Latin)": "msi_Latn",
    "Mswahili (Latin)": "msw_Latn",
    "Malay (macrolanguage) (Latin)": "msy_Latn",
    "Mator-Taygi-Karagas (Latin)": "mtd_Latn",
    "Binukidnon (Latin)": "mtj_Latn",
    "Yosondúa Mixtec (Latin)": "mto_Latn",
    "Totontepec Mixe (Devanagari)": "mtr_Deva",
    "Tututepec Mixtec (Latin)": "mtu_Latn",
    "Tututepec Mixtec (Latin)": "mtx_Latn",
    "Mundang (Latin)": "mua_Latn",
    "Mubi (Latin)": "mug_Latn",
    "Mündü (Latin)": "muh_Latn",
    "Musi (Latin)": "mui_Latn",
    "Majhwar (Devanagari)": "mup_Deva",
    "Murle (Latin)": "mur_Latn",
    "Muthuvan (Malayalam)": "muv_Mlym",
    "Muyang (Latin)": "muy_Latn",
    "Marwari (Arabic)": "mve_Arab",
    "Marwari (Arabic)": "mvp_Latn",
    "Marwari (Arabic)": "mvy_Arab",
    "Mwanga (Tanzania) (Latin)": "mwq_Latn",
    "Mwera (Tanzania) (Latin)": "mwv_Latn",
    "Metlatónoc Mixtec (Latin)": "mxb_Latn",
    "Juxtlahuaca Mixtec (Latin)": "mxq_Latn",
    "Silacayoapan Mixtec (Latin)": "mxs_Latn",
    "Tezoatlán Mixtec (Latin)": "mxt_Latn",
    "Metlatónoc Mixtec (Latin)": "mxu_Latn",
    "Northwestern Ojibwa (Latin)": "mxv_Latn",
    "Metlatónoc Mixtec (Latin)": "mxy_Latn",
    "Burmese (Myanmar)": "mya_Mymr",
    "Mbay (Latin)": "myb_Latn",
    "Myene (Latin)": "myk_Latn",
    "Erzya (Cyrillic)": "myv_Cyrl",
    "Masa (Chad) (Latin)": "myx_Latn",
    "Macuna (Latin)": "myy_Latn",
    "Santa María Zacatepec Mixtec (Latin)": "mza_Latn",
    "Berber languages (Latin)": "mzi_Latn",
    "Mazatlán Mixe (Latin)": "mzj_Latn",
    "Mazatlán Mixe (Latin)": "mzk_Latn",
    "Mazatlán Mixe (Latin)": "mzl_Latn",
    "Mumuye (Latin)": "mzm_Latn",
    "Manado Malay (Latin)": "mzw_Latn",
    "Nimanbur (Latin)": "nab_Latn",
    "Naga languages (Latin)": "nag_Latn",
    "Nalik (Latin)": "nal_Latn",
    "Min Nan Chinese (Latin)": "nan_Latn",
    "Neapolitan (Latin)": "nap_Latn",
    "Coatepec Nahuatl (Latin)": "nas_Latn",
    "Nawuri (Latin)": "naw_Latn",
    "Nyemba (Latin)": "nbh_Latn",
    "Chang Naga (Latin)": "nca_Latn",
    "Notsi (Latin)": "ncf_Latn",
    "Central Huasteca Nahuatl (Latin)": "nch_Latn",
    "Central Puebla Nahuatl (Latin)": "ncj_Latn",
    "Michoacán Nahuatl (Latin)": "ncl_Latn",
    "N eko (Latin)": "nco_Latn",
    "Nahuatl languages (Latin)": "ncu_Latn",
    "Morelos Nahuatl (Latin)": "ncx_Latn",
    "Ndogo (Latin)": "ndi_Latn",
    "Ndjuká (Latin)": "ndj_Latn",
    "Ndonga (Latin)": "ndo_Latn",
    "Ndo (Latin)": "ndp_Latn",
    "Ndut (Latin)": "ndv_Latn",
    "Lutos (Latin)": "ndy_Latn",
    "Ndogo (Latin)": "ndz_Latn",
    "Toura (Côte d'Ivoire) (Latin)": "neb_Latn",
    "Nepali (Devanagari)": "nep_Deva",
    "Newari (Devanagari)": "new_Deva",
    "Ngbaka'ma'bo (Latin)": "nfa_Latn",
    "Nefamese (Latin)": "nfr_Latn",
    "Ngad'a (Latin)": "nga_Latn",
    "Ngemba (Latin)": "ngi_Latn",
    "Lomwe (Latin)": "ngl_Latn",
    "Ngulu (Latin)": "ngp_Latn",
    "Guerrero Nahuatl (Latin)": "ngu_Latn",
    "Eastern Huasteca Nahuatl (Latin)": "nhe_Latn",
    "Ngiyambaa (Latin)": "nhg_Latn",
    "Zacatlán-Ahuacatlán-Tepetzintla Nahuatl (Latin)": "nhi_Latn",
    "Nahari (Latin)": "nhn_Latn",
    "Tetelcingo Nahuatl (Latin)": "nhq_Latn",
    "Orizaba Nahuatl (Latin)": "nhu_Latn",
    "Western Huasteca Nahuatl (Latin)": "nhw_Latn",
    "Tabasco Nahuatl (Latin)": "nhx_Latn",
    "Ometepec Nahuatl (Latin)": "nhy_Latn",
    "Nias (Latin)": "nia_Latn",
    "Ngaju (Latin)": "nij_Latn",
    "Nimi (Latin)": "nim_Latn",
    "Ninzo (Latin)": "nin_Latn",
    "Nganasan (Latin)": "nja_Latn",
    "Nkonya (Latin)": "nko_Latn",
    "Ngombale (Latin)": "nla_Latn",
    "Ná-Meo (Latin)": "nlc_Latn",
    "Dutch (Latin)": "nld_Latn",
    "Gela (Latin)": "nlg_Latn",
    "Ninia Yali (Latin)": "nlk_Latn",
    "Orizaba Nahuatl (Latin)": "nlv_Latn",
    "Nyamwezi (Latin)": "nmg_Latn",
    "Nyamwezi (Latin)": "nmz_Latn",
    "Norwegian Nynorsk (Latin)": "nnb_Latn",
    "Ngiemboon (Latin)": "nnh_Latn",
    "Ngen (Latin)": "nnq_Latn",
    "Nuni (Latin)": "nnw_Latn",
    "Nocamán (Latin)": "noa_Latn",
    "Norwegian Bokmål (Latin)": "nob_Latn",
    "Northern Thai (Thai)": "nod_Thai",
    "Nimadi (Devanagari)": "noe_Deva",
    "Nogai (Cyrillic)": "nog_Cyrl",
    "Nomatsiguenga (Latin)": "not_Latn",
    "Nupoid languages (Latin)": "npl_Latn",
    "Napu (Latin)": "npy_Latn",
    "Northern Sotho (Latin)": "nso_Latn",
    "Nisenan (Latin)": "nst_Latn",
    "Nisu (Latin)": "nsu_Latn",
    "Naga languages (Latin)": "ntm_Latn",
    "Ntrubo (Latin)": "ntr_Latn",
    "Nobsalan (Latin)": "nuj_Latn",
    "Nung (Viet Nam) (Latin)": "nup_Latn",
    "Nuer (Latin)": "nus_Latn",
    "Nuu-chah-nulth (Latin)": "nuz_Latn",
    "Nyabwa (Latin)": "nwb_Latn",
    "Naxi (Latin)": "nxq_Latn",
    "Nyanja (Latin)": "nya_Latn",
    "Nyanga-li (Latin)": "nyf_Latn",
    "Nyankole (Latin)": "nyn_Latn",
    "Nyoro (Latin)": "nyo_Latn",
    "Nyulnyul (Latin)": "nyu_Latn",
    "Nyulnyul (Latin)": "nyy_Latn",
    "Nzima (Latin)": "nzi_Latn",
    "Obo Manobo (Latin)": "obo_Latn",
    "Occitan (post 1500) (Latin)": "oci_Latn",
    "Ormuri (Arabic)": "odk_Arab",
    "Odual (Latin)": "odu_Latn",
    "Ogoniland (Latin)": "ogo_Latn",
    "Ojibwa (Canadian Aboriginal Syllabics)": "ojb_Cans",
    "Ojibwa (Latin)": "ojb_Latn",
    "Oku (Latin)": "oku_Latn",
    "Mochi (Latin)": "old_Latn",
    "Omejes (Latin)": "omw_Latn",
    "Obo Manobo (Latin)": "onb_Latn",
    "Tohono O'odham (Latin)": "ood_Latn",
    "Oroqen (Latin)": "orc_Latn",
    "Oromo (Latin)": "orm_Latn",
    "Ormuri (Arabic)": "oru_Arab",
    "Oriya (Oriya)": "ory_Orya",
    "Ossetian (Cyrillic)": "oss_Cyrl",
    "Otomi (Latin)": "ote_Latn",
    "Otomi (Latin)": "otq_Latn",
    "Old Turkish (Latin)": "ozm_Latn",
    "Páez (Latin)": "pab_Latn",
    "Pareci (Latin)": "pad_Latn",
    "Pangasinan (Latin)": "pag_Latn",
    "Pampanga (Latin)": "pam_Latn",
    "Panjabi (Gurmukhi)": "pan_Guru",
    "Northern Paiute (Latin)": "pao_Latn",
    "Papiamento (Latin)": "pap_Latn",
    "Palauan (Latin)": "pau_Latn",
    "Pangwa (Latin)": "pbb_Latn",
    "Patamona (Latin)": "pbc_Latn",
    "Mezontla Popoloca (Latin)": "pbi_Latn",
    "Parkwa (Latin)": "pbs_Latn",
    "Southern Pashto (Arabic)": "pbt_Arab",
    "Northern Pashto (Arabic)": "pbu_Arab",
    "Ruching Palaung (Thai)": "pce_Thai",
    "Nigerian Pidgin (Latin)": "pcm_Latn",
    "Pardhan (Latin)": "pex_Latn",
    "Eastern Pomo (Latin)": "pez_Latn",
    "Pahi (Arabic)": "phl_Arab",
    "Phuan (Arabic)": "phr_Arab",
    "Pima Bajo (Latin)": "pib_Latn",
    "Yinjtjiparnti (Latin)": "pil_Latn",
    "Piapoco (Latin)": "pip_Latn",
    "Piratapuyo (Latin)": "pir_Latn",
    "Pijin (Latin)": "pis_Latn",
    "Pitta Pitta (Latin)": "piy_Latn",
    "Pijao (Latin)": "pjt_Latn",
    "Pokomo (Latin)": "pkb_Latn",
    "Pökoot (Latin)": "pko_Latn",
    "Shwe Palaung (Arabic)": "plk_Arab",
    "Central Pame (Latin)": "pls_Latn",
    "Malagasy, Plateau (Latin)": "plt_Latn",
    "Polonombauk (Latin)": "plw_Latn",
    "Piemontese (Latin)": "pmf_Latn",
    "Piemontese (Latin)": "pmq_Latn",
    "Piemontese (Latin)": "pms_Latn",
    "Pamona (Latin)": "pmy_Latn",
    "Western Panjabi (Arabic)": "pnb_Arab",
    "Penesak (Latin)": "pne_Latn",
    "Pinyin (Latin)": "pny_Latn",
    "Ponares (Latin)": "poc_Latn",
    "Poqomam (Latin)": "poe_Latn",
    "Poqomchi' (Latin)": "poh_Latn",
    "Pokangá (Latin)": "poi_Latn",
    "Polish (Latin)": "pol_Latn",
    "Portuguese (Latin)": "por_Latn",
    "Pémono (Latin)": "pov_Latn",
    "Puelche (Latin)": "pow_Latn",
    "Puelche (Latin)": "poy_Latn",
    "Paipai (Latin)": "ppk_Latn",
    "San Luís Temalacayuca Popoloca (Latin)": "pps_Latn",
    "Pa'o (Latin)": "prf_Latn",
    "Parauk (Latin)": "prk_Latn",
    "Parsi-Dari (Latin)": "prq_Latn",
    "Phai (Thai)": "prt_Thai",
    "Pai Tavytera (Latin)": "pse_Latn",
    "Kaulong (Latin)": "pss_Latn",
    "Central Pashto (Arabic)": "pst_Arab",
    "Patuá (Latin)": "ptu_Latn",
    "Punan Merap (Latin)": "pua_Latn",
    "Punan Merap (Latin)": "pui_Latn",
    "Pushto (Arabic)": "pus_Arab",
    "Pangwali (Latin)": "pwg_Latn",
    "Paiwan (Latin)": "pwn_Latn",
    "Pwo Western Karen (Thai)": "pww_Thai",
    "Quetzaltepec Mixe (Latin)": "pxm_Latn",
    "Bikol (Latin)": "qub_Latn",
    "K'iche' (Latin)": "quc_Latn",
    "Lambayeque Quechua (Latin)": "quf_Latn",
    "Chimborazo Highland Quichua (Latin)": "qug_Latn",
    "South Bolivian Quechua (Latin)": "quh_Latn",
    "North Bolivian Quechua (Latin)": "qul_Latn",
    "Sipacapense (Latin)": "qum_Latn",
    "Panao Huánuco Quechua (Latin)": "qup_Latn",
    "Yanahuanca Pasco Quechua (Latin)": "qur_Latn",
    "Southern Pastaza Quechua (Latin)": "qus_Latn",
    "Quechua (Latin)": "quv_Latn",
    "Quechua (Latin)": "quw_Latn",
    "Quechua (Latin)": "qux_Latn",
    "Ayacucho Quechua (Latin)": "quy_Latn",
    "Cusco Quechua (Latin)": "quz_Latn",
    "Ambo-Pasco Quechua (Latin)": "qva_Latn",
    "Cajamarca Quechua (Latin)": "qvc_Latn",
    "Eastern Apurímac Quechua (Latin)": "qve_Latn",
    "Huallaga Huánuco Quechua (Latin)": "qvh_Latn",
    "Imbabura Highland Quichua (Latin)": "qvi_Latn",
    "Loja Highland Quichua (Latin)": "qvj_Latn",
    "Cajatambo North Lima Quechua (Latin)": "qvl_Latn",
    "Margos-Yarowilca-Lauricocha Quechua (Latin)": "qvm_Latn",
    "North Junín Quechua (Latin)": "qvn_Latn",
    "Napo Lowland Quechua (Latin)": "qvo_Latn",
    "San Martín Quechua (Latin)": "qvs_Latn",
    "Huaylla Wanca Quechua (Latin)": "qvw_Latn",
    "Yauyos Quechua (Latin)": "qvz_Latn",
    "Corongo Ancash Quechua (Latin)": "qwa_Latn",
    "Huaylas Ancash Quechua (Latin)": "qwh_Latn",
    "Sihuas Ancash Quechua (Latin)": "qws_Latn",
    "Chiquián Ancash Quechua (Latin)": "qxa_Latn",
    "Southern Conchucos Ancash Quechua (Latin)": "qxh_Latn",
    "Northern Conchucos Ancash Quechua (Latin)": "qxl_Latn",
    "Puno Quechua (Latin)": "qxn_Latn",
    "Southern Pastaza Quechua (Latin)": "qxo_Latn",
    "Puno Quechua (Latin)": "qxp_Latn",
    "Pacaraos Quechua (Latin)": "qxr_Latn",
    "Santa Ana de Tusi Pasco Quechua (Latin)": "qxt_Latn",
    "Arequipa-La Unión Quechua (Latin)": "qxu_Latn",
    "Jauja Wanca Quechua (Latin)": "qxw_Latn",
    "Rāga (Latin)": "rag_Latn",
    "Rahambuu (Bengali)": "rah_Beng",
    "Ramoaaina (Latin)": "rai_Latn",
    "Rapa Nui (Latin)": "rap_Latn",
    "Rawang (Devanagari)": "rav_Deva",
    "Rawang (Latin)": "raw_Latn",
    "Rejang (Latin)": "rej_Latn",
    "Rendille (Latin)": "rel_Latn",
    "Raguile (Latin)": "rgu_Latn",
    "Rohingya (Latin)": "rhg_Latn",
    "Tarifit (Arabic)": "rif_Arab",
    "Tarifit (Latin)": "rif_Latn",
    "Riang (India) (Latin)": "rim_Latn",
    "Riang (India) (Devanagari)": "rjs_Deva",
    "Rangpuri (Bengali)": "rkt_Beng",
    "Carpathian Romani (Cyrillic)": "rmc_Cyrl",
    "Carpathian Romani (Latin)": "rmc_Latn",
    "Traveller Norwegian (Latin)": "rmo_Latn",
    "Romany (Cyrillic)": "rmy_Cyrl",
    "Romany (Latin)": "rmy_Latn",
    "Roon (Latin)": "rng_Latn",
    "Roon (Latin)": "rnl_Latn",
    "Tae' (Latin)": "rob_Latn",
    "Rombo (Latin)": "rof_Latn",
    "Romansh (Latin, surs1244)": "roh_Latn_surs1244",
    "Romblomanon (Latin)": "rol_Latn",
    "Romanian (Latin)": "ron_Latn",
    "Rongga (Latin)": "roo_Latn",
    "Kriol (Latin)": "rop_Latn",
    "Rotokas (Latin)": "rro_Latn",
    "Rathawi (Latin)": "rth_Latn",
    "Rusyn (Latin)": "rub_Latn",
    "Ruuli (Latin)": "ruc_Latn",
    "Rufiji (Latin)": "ruf_Latn",
    "Ruga (Latin)": "rug_Latn",
    "Rundi (Latin)": "run_Latn",
    "Russian (Cyrillic)": "rus_Cyrl",
    "Mbwela (Latin)": "rwm_Latn",
    "Marwari (India) (Devanagari)": "rwr_Deva",
    "Saba (Latin)": "sab_Latn",
    "Sango (Latin)": "sag_Latn",
    "Yakut (Cyrillic)": "sah_Cyrl",
    "Sahu (Latin)": "saj_Latn",
    "Samburu (Latin)": "saq_Latn",
    "Sasak (Latin)": "sas_Latn",
    "Sause (Latin)": "sau_Latn",
    "Sayula Popoluca (Latin)": "say_Latn",
    "Ngambay (Latin)": "sba_Latn",
    "Simbo (Latin)": "sbd_Latn",
    "Sagala (Latin)": "sbl_Latn",
    "Sindhi Bhil (Arabic)": "sbn_Arab",
    "Sangu (Tanzania) (Latin)": "sbp_Latn",
    "Sangu (Gabon) (Latin)": "sch_Latn",
    "Sadri (Devanagari)": "sck_Deva",
    "Shina (Arabic)": "scl_Arab",
    "Sicilian (Latin)": "scn_Latn",
    "Scots (Latin)": "sco_Latn",
    "Sandawe (Latin)": "sda_Latn",
    "Sardo-logudorese (Latin)": "sdo_Latn",
    "Semai (Latin)": "sea_Latn",
    "Sena (Latin)": "seh_Latn",
    "Sena (Latin)": "sei_Latn",
    "Serrano (Latin)": "ses_Latn",
    "Serrano (Latin)": "sey_Latn",
    "Sangu (Gabon) (Latin)": "sgb_Latn",
    "Surgujia (Devanagari)": "sgj_Deva",
    "Suri (Ethiopic)": "sgw_Ethi",
    "Tachelhit (Latin)": "shi_Latn",
    "Sheko (Latin)": "shk_Latn",
    "Shan (Myanmar)": "shn_Mymr",
    "Shanga (Latin)": "sho_Latn",
    "Sala (Latin)": "shp_Latn",
    "Sidamo (Latin)": "sid_Latn",
    "Serrano (Latin)": "sig_Latn",
    "Tumulung Sisaala (Latin)": "sil_Latn",
    "Sinhala (Sinhala)": "sin_Sinh",
    "Sikkimese (Tibetan)": "sip_Tibt",
    "Siwa (Latin)": "siw_Latn",
    "Soli (Latin)": "sja_Latn",
    "Simaa (Latin)": "sjm_Latn",
    "Surjapuri (Devanagari)": "sjp_Deva",
    "Siar-Lak (Latin)": "sjr_Latn",
    "Seke (Vanuatu) (Latin)": "skg_Latn",
    "Saraiki (Arabic)": "skr_Arab",
    "Sáliba (Latin)": "sld_Latn",
    "Slovak (Latin)": "slk_Latn",
    "Selaru (Latin)": "slu_Latn",
    "Slovenian (Latin)": "slv_Latn",
    "Sama (Latin)": "sml_Latn",
    "Samoan (Latin)": "smo_Latn",
    "Shona (Latin)": "sna_Latn",
    "Sanga (Nigeria) (Latin)": "snc_Latn",
    "Sindhi (Arabic)": "snd_Arab",
    "Bau Bidayuh (Latin)": "sne_Latn",
    "Soninke (Latin)": "snk_Latn",
    "Siona (Latin)": "snn_Latn",
    "Siane (Latin)": "snp_Latn",
    "Sauk (Latin)": "snv_Latn",
    "Sauk (Latin)": "snw_Latn",
    "Solos (Latin)": "sol_Latn",
    "Somali (Latin)": "som_Latn",
    "Songe (Latin)": "soy_Latn",
    "Spanish (Latin)": "spa_Latn",
    "Sian (Latin)": "spp_Latn",
    "Saponi (Latin)": "sps_Latn",
    "Sabaot (Latin)": "spy_Latn",
    "Sardinian (Latin)": "src_Latn",
    "Sardinian (Latin)": "srd_Latn",
    "Sera (Latin)": "sri_Latn",
    "Saramaccan (Latin)": "srm_Latn",
    "Sranan Tongo (Latin)": "srn_Latn",
    "Sarsuti (Latin)": "sro_Latn",
    "Serbian (Cyrillic)": "srp_Cyrl",
    "Serer (Latin)": "srr_Latn",
    "Seraiki (Devanagari)": "srx_Deva",
    "Siri (Arabic)": "ssi_Arab",
    "Seta (Latin)": "ste_Latn",
    "Sateré-Mawé (Latin)": "stn_Latn",
    "Stieng (Latin)": "stp_Latn",
    "Sua (Latin)": "sua_Latn",
    "Suku (Latin)": "suc_Latn",
    "Sukuma (Latin)": "suk_Latn",
    "Sundanese (Latin)": "sun_Latn",
    "Suri (Latin)": "sur_Latn",
    "Susu (Latin)": "sus_Latn",
    "Susu (Latin)": "suv_Latn",
    "Sunwar (Devanagari)": "suz_Deva",
    "Svan (Georgian)": "sva_Geor",
    "Swedish (Latin)": "swe_Latn",
    "Swahili (macrolanguage) (Latin)": "swh_Latn",
    "Seraiki (Devanagari)": "swv_Deva",
    "Sumbwa (Latin)": "sxb_Latn",
    "Sicanian (Latin)": "sxn_Latn",
    "Sighu (Latin)": "sya_Latn",
    "Sylheti (Latin)": "syl_Latn",
    "Saurashtra (Latin)": "sza_Latn",
    "Saurashtra (Latin)": "szy_Latn",
    "Tuma-Irumu (Latin)": "tac_Latn",
    "Tajio (Devanagari)": "taj_Deva",
    "Tamil (Tamil)": "tam_Taml",
    "Tana (Latin)": "tan_Latn",
    "Tangale (Latin)": "tao_Latn",
    "Taabwa (Latin)": "tap_Latn",
    "Tarahumara (Latin)": "taq_Latn",
    "Central Tarahumara (Latin)": "tar_Latn",
    "Tatar (Cyrillic)": "tat_Cyrl",
    "Tatuyo (Latin)": "tav_Latn",
    "Tay (Latin)": "tay_Latn",
    "Taliabu (Latin)": "tbc_Latn",
    "Kbo (Latin)": "tbf_Latn",
    "Tairora (Latin)": "tbg_Latn",
    "Tboli (Latin)": "tbk_Latn",
    "Tboli (Latin)": "tbl_Latn",
    "Tagbu (Latin)": "tby_Latn",
    "Ditammari (Latin)": "tbz_Latn",
    "Ticuna (Latin)": "tca_Latn",
    "Datooga (Latin)": "tcc_Latn",
    "Malagasy, Tsimihety (Latin)": "tcf_Latn",
    "Tulu (Malayalam)": "tcy_Mlym",
    "Are'are (Latin)": "tcz_Latn",
    "Tidong (Latin)": "tdj_Latn",
    "Tandaganon (Latin)": "tdn_Latn",
    "Tandroy-Mahafaly Malagasy (Latin)": "tdx_Latn",
    "Tepo Krumen (Latin)": "ted_Latn",
    "Teressa (Latin)": "tee_Latn",
    "Telugu (Telugu)": "tel_Telu",
    "Timne (Latin)": "tem_Latn",
    "Teso (Latin)": "teo_Latn",
    "Teso (Latin)": "ter_Latn",
    "Tewa (USA) (Latin)": "tew_Latn",
    "Tennet (Latin)": "tex_Latn",
    "Terik (Latin)": "tfr_Latn",
    "Ternate (Latin)": "tgc_Latn",
    "Togoyo (Latin)": "tgj_Latn",
    "Tajik (Cyrillic)": "tgk_Cyrl",
    "Tagalog (Latin)": "tgl_Latn",
    "Togoyo (Latin)": "tgo_Latn",
    "Togoyo (Latin)": "tgp_Latn",
    "Thai (Thai)": "tha_Thai",
    "Tharu (Devanagari)": "the_Deva",
    "Tho (Latin)": "thk_Latn",
    "Tharu (Devanagari)": "thl_Deva",
    "Tharu (Devanagari)": "thq_Deva",
    "Tharu (Devanagari)": "thr_Deva",
    "Thangmi (Tifinagh)": "thv_Tfng",
    "Tigre (Ethiopic)": "tig_Ethi",
    "Timugon Murut (Latin)": "tih_Latn",
    "Tii (Latin)": "tik_Latn",
    "Tillamook (Latin)": "tio_Latn",
    "Tigrinya (Ethiopic)": "tir_Ethi",
    "Masaka (Latin)": "tkg_Latn",
    "Tukumanféd (Latin)": "tkr_Latn",
    "Takpa (Devanagari)": "tkt_Deva",
    "Tobo-Kube (Latin)": "tlb_Latn",
    "Tlingit (Latin)": "tli_Latn",
    "Talysh (Latin)": "tlj_Latn",
    "Taloki (Latin)": "tlp_Latn",
    "Talysh (Latin)": "tly_Latn",
    "Tumak (Latin)": "tmc_Latn",
    "Toba-Maskoy (Latin)": "tmf_Latn",
    "Tasmate (Latin)": "tna_Latn",
    "Tonga (Nyasa) (Latin)": "tng_Latn",
    "Tenis (Latin)": "tnk_Latn",
    "Tonsawang (Latin)": "tnn_Latn",
    "Tontemboan (Latin)": "tnp_Latn",
    "Ménik (Latin)": "tnr_Latn",
    "Tenino (Latin)": "tnt_Latn",
    "Toba (Latin)": "tob_Latn",
    "Coyutla Totonac (Latin)": "toc_Latn",
    "Toma (Latin)": "toh_Latn",
    "Toki Pona (Latin)": "tok_Latn",
    "Tomini (Latin)": "tom_Latn",
    "Xicotepec De Juárez Totonac (Latin)": "top_Latn",
    "Tukumanféd (Latin)": "tos_Latn",
    "Tok Pisin (Latin)": "tpi_Latn",
    "Tukumanféd (Latin)": "tpl_Latn",
    "Tampulma (Latin)": "tpm_Latn",
    "Tukumanféd (Latin)": "tpp_Latn",
    "Tukumanféd (Latin)": "tpt_Latn",
    "Tukumanféd (Latin)": "tpz_Latn",
    "Tukumanféd (Latin)": "tqp_Latn",
    "Trio (Latin)": "trc_Latn",
    "Turi (Latin)": "tri_Latn",
    "Torona (Latin)": "trn_Latn",
    "Trumai (Latin)": "trp_Latn",
    "Tregami (Latin)": "trq_Latn",
    "Tirahi (Latin)": "trs_Latn",
    "Trukhmen (Latin)": "trv_Latn",
    "Torwali (Arabic)": "trw_Arab",
    "Tswana (Latin)": "tsn_Latn",
    "Tsonga (Latin)": "tso_Latn",
    "Tsuvan (Latin)": "tsz_Latn",
    "Tswa (Latin)": "ttc_Latn",
    "Tutelo (Latin)": "tte_Latn",
    "Tooro (Latin)": "ttj_Latn",
    "Tawallammat Tamajaq (Tifinagh)": "ttq_Tfng",
    "Tutoro (Latin)": "ttr_Latn",
    "Wotu (Latin)": "ttu_Latn",
    "Tübatulabal (Latin)": "tue_Latn",
    "Tübatulabal (Latin)": "tuf_Latn",
    "Tugutil (Latin)": "tui_Latn",
    "Turkmen (Arabic)": "tuk_Arab",
    "Turkmen (Latin)": "tuk_Latn",
    "Tula (Latin)": "tul_Latn",
    "Tumbuka (Latin)": "tuo_Latn",
    "Tedaga (Latin)": "tuq_Latn",
    "Turkish (Latin)": "tur_Latn",
    "Tuxináwa (Latin)": "tuv_Latn",
    "Tuxináwa (Latin)": "tuy_Latn",
    "Tungus languages (Latin)": "tvo_Latn",
    "Tungus languages (Latin)": "tvu_Latn",
    "Tungus languages (Latin)": "tvw_Latn",
    "Tawbuid (Latin)": "twb_Latn",
    "Twents (Latin)": "twe_Latn",
    "Tungus languages (Latin)": "twu_Latn",
    "Tewe (Latin)": "txa_Latn",
    "Tombonuo (Latin)": "txq_Latn",
    "Tartessian (Latin)": "txs_Latn",
    "Kayapó (Latin)": "txu_Latn",
    "Tanosy Malagasy (Latin)": "txy_Latn",
    "Tauya (Latin)": "tye_Latn",
    "Tzeltal (Latin)": "tzh_Latn",
    "Tz'utujil (Latin)": "tzj_Latn",
    "Tzotzil (Latin)": "tzo_Latn",
    "Ubi (Latin)": "ubl_Latn",
    "Ubang (Latin)": "ubu_Latn",
    "Ujir (Latin)": "udl_Latn",
    "Udmurt (Cyrillic)": "udm_Cyrl",
    "Uduk (Latin)": "udu_Latn",
    "Uighur (Arabic)": "uig_Arab",
    "Uighur (Cyrillic)": "uig_Cyrl",
    "Ukuriguma (Oriya)": "uki_Orya",
    "Ukrainian (Cyrillic)": "ukr_Cyrl",
    "Ukuriguma (Latin)": "ukv_Latn",
    "Umbundu (Latin)": "umb_Latn",
    "Uripiv-Wala-Rano-Atchin (Latin)": "upv_Latn",
    "Ura (Vanuatu) (Latin)": "ura_Latn",
    "Urubú-Kaapor (Latin)": "urb_Latn",
    "Urdu (Arabic)": "urd_Arab",
    "Urdu (Devanagari)": "urd_Deva",
    "Urdu (Latin)": "urd_Latn",
    "Urhobo (Latin)": "urh_Latn",
    "Urak Lawoi' (Thai)": "urk_Thai",
    "Urat (Latin)": "urt_Latn",
    "Uru (Latin)": "ury_Latn",
    "Ushojo (Arabic)": "ush_Arab",
    "Uspanteco (Latin)": "usp_Latn",
    "Uzbek (Cyrillic)": "uzb_Cyrl",
    "Uzbek (Latin)": "uzb_Latn",
    "Northern Uzbek (Latin)": "uzn_Latn",
    "Vagla (Latin)": "vag_Latn",
    "Varhadi-Nagpuri (Devanagari)": "vah_Deva",
    "Vehes (Latin)": "vai_Latn",
    "Varli (Latin)": "var_Latn",
    "Veluws (Latin)": "ver_Latn",
    "Vinde (Latin)": "vid_Latn",
    "Vietnamese (Latin)": "vie_Latn",
    "Vili (Latin)": "vif_Latn",
    "Viemo (Latin)": "vmc_Latn",
    "Juxtlahuaca Mixtec (Latin)": "vmj_Latn",
    "Mitlatongo Mixtec (Latin)": "vmm_Latn",
    "Soyaltepec Mazatec (Latin)": "vmp_Latn",
    "Makhuwa (Latin)": "vmw_Latn",
    "Soyaltepec Mazatec (Latin)": "vmy_Latn",
    "Soyaltepec Mazatec (Latin)": "vmz_Latn",
    "Võro (Latin)": "vro_Latn",
    "Vunjo (Latin)": "vun_Latn",
    "Vute (Latin)": "vut_Latn",
    "Wolaytta (Ethiopic)": "wal_Ethi",
    "Wolaytta (Latin)": "wal_Latn",
    "Wapishana (Latin)": "wap_Latn",
    "Waray (Philippines) (Latin)": "war_Latn",
    "Walla Walla (Latin)": "waw_Latn",
    "Wayana (Latin)": "way_Latn",
    "Warao (Latin)": "wba_Latn",
    "Wakhi (Latin)": "wbl_Latn",
    "Wagdi (Devanagari)": "wbr_Deva",
    "Waci Gbe (Latin)": "wci_Latn",
    "Wè Western (Latin)": "weo_Latn",
    "Wewaw (Latin)": "wes_Latn",
    "Wajan (Latin)": "wja_Latn",
    "Warji (Latin)": "wji_Latn",
    "Walloon (Latin)": "wlo_Latn",
    "Wolio (Latin)": "wlx_Latn",
    "Womo (Latin)": "wmw_Latn",
    "Wobé (Latin)": "wob_Latn",
    "Wolof (Latin)": "wof_Latn",
    "Wolof (Latin)": "wol_Latn",
    "Wagdi (Telugu)": "wsg_Telu",
    "Wassa (Latin)": "wwa_Latn",
    "Kalmyk (Cyrillic)": "xal_Cyrl",
    "Kayan Mahakam (Latin)": "xdy_Latn",
    "Xerénte (Latin)": "xed_Latn",
    "Xerénte (Latin)": "xer_Latn",
    "Khetrani (Arabic)": "xhe_Arab",
    "Xhosa (Latin)": "xho_Latn",
    "Kalkoti (Arabic)": "xka_Arab",
    "Kalkoti (Latin)": "xkl_Latn",
    "Mingrelian (Georgian)": "xmf_Geor",
    "Malay (macrolanguage), Malaccan (Latin)": "xmm_Latn",
    "Mean (Latin)": "xmv_Latn",
    "Kenyan Sign Language (Latin)": "xnj_Latn",
    "Kanjar (Devanagari)": "xnr_Deva",
    "Xhosa (Latin)": "xog_Latn",
    "Komo (Sudan) (Latin)": "xon_Latn",
    "Kpelle (Latin)": "xpe_Latn",
    "Karahawyana (Latin)": "xrb_Latn",
    "Samberigi (Latin)": "xsb_Latn",
    "Samberigi (Latin)": "xsm_Latn",
    "Sherpa (Devanagari)": "xsr_Deva",
    "Sukur (Latin)": "xsu_Latn",
    "Alcozauca Mixtec (Latin)": "xta_Latn",
    "Diuxi-Tilantongo Mixtec (Latin)": "xtd_Latn",
    "Ketengban (Latin)": "xte_Latn",
    "Sino-Tibetan languages (Latin)": "xti_Latn",
    "Tidaá Mixtec (Latin)": "xtm_Latn",
    "Diuxi-Tilantongo Mixtec (Latin)": "xtn_Latn",
    "Cuyamecalco Mixtec (Latin)": "xtu_Latn",
    "Alcozauca Mixtec (Tamil)": "xua_Taml",
    "Kuo (Latin)": "xuo_Latn",
    "Yaminahua (Latin)": "yaa_Latn",
    "Yagua (Latin)": "yad_Latn",
    "Yalunka (Latin)": "yal_Latn",
    "Yamba (Latin)": "yam_Latn",
    "Yao (Latin)": "yao_Latn",
    "Yagua (Latin)": "yaq_Latn",
    "Yagua (Latin)": "yas_Latn",
    "Yagua (Latin)": "yat_Latn",
    "Yavanawa (Latin)": "yav_Latn",
    "Yei (Latin)": "yay_Latn",
    "Yazgulyam (Latin)": "yaz_Latn",
    "Yala (Latin)": "yba_Latn",
    "Yemba (Latin)": "ybb_Latn",
    "Yucatec Maya Sign Language (Latin)": "ycl_Latn",
    "Yucuna (Latin)": "ycn_Latn",
    "Yiddish (Hebrew)": "ydd_Hebr",
    "Yidgha (Arabic)": "ydg_Arab",
    "Yennu (Malayalam)": "yea_Mlym",
    "Yenisei Say (Latin)": "yer_Latn",
    "Yeskwa (Latin)": "yes_Latn",
    "Yaka (Congo) (Latin)": "yka_Latn",
    "Yalo (Latin)": "yli_Latn",
    "Yoruba (Latin)": "yor_Latn",
    "Yarí (Latin)": "yre_Latn",
    "Yucateco (Latin)": "yua_Latn",
    "Yue Chinese (Han)": "yue_Hans",
    "Yue Chinese (Han)": "yue_Hant",
    "Yuracare (Latin)": "yuz_Latn",
    "Yawa (Latin)": "yva_Latn",
    "Zapotec (Latin)": "zaa_Latn",
    "Zapotec (Latin)": "zab_Latn",
    "Ocotlán Zapotec (Latin)": "zac_Latn",
    "Cajonos Zapotec (Latin)": "zad_Latn",
    "Yareni Zapotec (Latin)": "zae_Latn",
    "Isthmus Zapotec (Latin)": "zai_Latn",
    "Miahuatlán Zapotec (Latin)": "zam_Latn",
    "Ozolotepec Zapotec (Latin)": "zao_Latn",
    "Aloápam Zapotec (Latin)": "zaq_Latn",
    "Rincón Zapotec (Latin)": "zar_Latn",
    "Santo Domingo Albarradas Zapotec (Latin)": "zas_Latn",
    "Yatzachi Zapotec (Latin)": "zav_Latn",
    "Zay (Latin)": "zaw_Latn",
    "Choapan Zapotec (Latin)": "zca_Latn",
    "Zhigulevsk (Latin)": "zga_Latn",
    "Zimza (Latin)": "zim_Latn",
    "Zinza (Latin)": "ziw_Latn",
    "Zialo (Latin)": "zmz_Latn",
    "Zande (macrolanguage) (Latin)": "zne_Latn",
    "Zoque (Latin)": "zoc_Latn",
    "Zoque (Latin)": "zoh_Latn",
    "Zoque (Latin)": "zor_Latn",
    "Zoque (Latin)": "zos_Latn",
    "Coatecas Altas Zapotec (Latin)": "zpc_Latn",
    "Guevea De Humboldt Zapotec (Latin)": "zpg_Latn",
    "Santa María Quiegolani Zapotec (Latin)": "zpi_Latn",
    "Lachixío Zapotec (Latin)": "zpl_Latn",
    "Mixtepec Zapotec (Latin)": "zpm_Latn",
    "Choapan Zapotec (Latin)": "zpo_Latn",
    "El Alto Zapotec (Latin)": "zpt_Latn",
    "San Vicente Coatlán Zapotec (Latin)": "zpv_Latn",
    "Chichicapan Zapotec (Latin)": "zpy_Latn",
    "Mazaltepec Zapotec (Latin)": "zpz_Latn",
    "Standard Malay (Latin)": "zsm_Latn",
    "Tlacolulita Zapotec (Latin)": "ztg_Latn",
    "Tataltepec Zapotec (Latin)": "ztn_Latn",
    "Tilquiapan Zapotec (Latin)": "ztp_Latn",
    "Quiavicuzas Zapotec (Latin)": "ztq_Latn",
    "Samo (Latin)": "zts_Latn",
    "Samo (Latin)": "ztu_Latn",
    "Yalálag Zapotec (Latin)": "zty_Latn",
    "Zulu (Latin)": "zul_Latn",
    "Yongbei Zhuang (Latin)": "zyb_Latn",
    "Yongbei Zhuang (Latin)": "zyp_Latn",
    "Zhuang (Latin)": "zza_Latn"
}
